services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:local
    pull_policy: never
    restart: unless-stopped
    env_file:
      - .env
    ports: 
      - "443:443"
    networks: 
      - webnet
    volumes:
      - webdata:/var/www/html
    depends_on:
      - wordpress
  
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:local
    pull_policy: never
    restart: unless-stopped
    secrets:
      - wp_admin_password
      - wp_user_password
      - db_password
    env_file:
      - .env
    networks: 
      - webnet
    volumes:
      - webdata:/var/www/html
    depends_on:
      - mariadb
  
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:local
    pull_policy: never
    restart: unless-stopped
    secrets:
      - db_password
    env_file:
      - .env
    networks:
      - webnet
    volumes:
      - dbdata:/var/lib/mysql

networks:
  webnet:
    name: webnet

volumes:
  webdata:
    name: webdata
  dbdata:
    name: dbdata

secrets:
  db_password:
    file: ../.secrets/db_password.txt
  wp_admin_password:
    file: ../.secrets/wp_admin_password.txt
  wp_user_password:
    file: ../.secrets/wp_user_password.txt