services:
  nginx:
    build: ./nginx
    ports: 
      - "8080:80"
    networks: 
      - webnet
    volumes:
      - webdata:/var/www/html
  wordpress:
    build: ./wordpress
    networks: 
      - webnet
    volumes:
      - webdata:/var/www/html
#   mariadb:
#     build: ./mariadb
#     networks:
#       - webnet
#     volumes:
#       - dbdata:/var/lib/mysql
networks:
  webnet:
volumes:
  webdata:
  dbdata: